blocks/columns/columns.css
Fix #58 
Test URLs:
- Before: https://main--oklahoma--aemdemos.aem.page/ocsw/about/history
- After: https://issue-58--oklahoma--aemdemos.aem.page/ocsw/about/history
=> columns history block

styles/styles.css
Fix #106
Test URLs:
- After: https://issue-106--oklahoma--aemdemos.aem.live/ocsw
=> Adjust font sizes for the body and headings

blocks/hero/hero.css
Fix #113
Test URLs:
Home:
Before: https://main--oklahoma--aemdemos.aem.live/ocsw
After: https://issue-113--oklahoma--aemdemos.aem.live/ocsw
Kate barnard (with link):
Before: https://main--oklahoma--aemdemos.aem.live/ocsw/kate-barnard
After: https://issue-113--oklahoma--aemdemos.aem.live/ocsw/kate-barnard
=> Implement default hero

blocks/header/header.css, blocks/header/header.js
Fix #112 
Test URLs:
- After: https://header-refinement--oklahoma--aemdemos.aem.live/ocsw
=> Header refinement

blocks/accordion/accordion.css, blocks/accordion/accordion.js, blocks/embed/embed.css
Fix #124 
Test URLs:
- Before: https://main--oklahoma--aemdemos.aem.page/ocsw/summits
- After: https://issue-124--oklahoma--aemdemos.aem.page/ocsw/summits
=> feat: implement video accordion

blocks/columns/columns.css, blocks/columns/columns.js, styles/styles.css
Fix #138 
Test URLs:
- After: https://issue-138--oklahoma--aemdemos.aem.live/ocsw
=> feat: style for columns(text-image) block

blocks/table/table.css
Fix #150 
Test URLs:
- Before: https://main--oklahoma--aemdemos.aem.live/ocsw/about/membership
- After: https://issue-150--oklahoma--aemdemos.aem.live/ocsw/about/membership
=> feat: columnar table style

blocks/cards/cards.css, blocks/cards/cards.js, styles/styles.css
Fix #152 
Test URLs:
- Before: https://main--oklahoma--aemdemos.aem.live/ocsw/awards
- After: https://awards-page--oklahoma--aemdemos.aem.live/ocsw/awards
=> feat: default styles + cards(multiple-images) variant

blocks/columns/columns.css, blocks/columns/columns.js
Fix #158 
Test URLs:
- Before: https://main--oklahoma--aemdemos.aem.live/ocsw/human-trafficking
- After: https://issue-158--oklahoma--aemdemos.aem.live/ocsw/human-trafficking
=> feat: style columns-2-1 variant

blocks/video/video.css, blocks/video/video.js
Fix #161 
Test URLs:
- Before: https://main--oklahoma--aemdemos.aem.live/ocsw/human-trafficking
- After: https://issue-161--oklahoma--aemdemos.aem.live/ocsw/human-trafficking
=> feat: video block

scripts/scripts.js
Fix #163 
Test URLs:
- Before: https://main--oklahoma--aemdemos.aem.live/ocsw/tap
- After: https://issue-163--oklahoma--aemdemos.aem.live/ocsw/tap
=> feat: external links to open in new tab

blocks/hero/hero.css, styles/styles.css
Test URLs:
- After: https://homepage-style--oklahoma--aemdemos.aem.live/ocsw
=> chore: default content style [homepage]

blocks/columns/columns.css, blocks/header/header.css, scripts/scripts.js, styles/styles.css
This PR fixes breadcrumbs, flex buttons on membership page, columns24 on homepage, bug when header menu on membership page
Test URLs:
- After: https://multiple-fixes--oklahoma--aemdemos.aem.live/ocsw
https://main--oklahoma--aemdemos.aem.live/ocsw/about/membership
https://multiple-fixes--oklahoma--aemdemos.aem.live/ocsw/about/membership
=> fix: multiple bugs and styles

blocks/hero/hero.css, styles/styles.css
Test URLs:
- After: https://multiple-fixes--oklahoma--aemdemos.aem.live/ocsw
https://main--oklahoma--aemdemos.aem.live/ocsw/about/membership
vs
https://multiple-fixes--oklahoma--aemdemos.aem.live/ocsw/about/membership
=> [Mobile View Fix] Hero and multiple-links div 

blocks/accordion/accordion.css
Fix #169 
Test URLs:
- Before: https://main--oklahoma--aemdemos.aem.live/ocsw/summits
- After: https://issue-169--oklahoma--aemdemos.aem.live/ocsw/summits
=> chore: fix styles for accordion7 and accordion(video)

blocks/columns/columns.css
Fix #156
Test URLs:
- Before: https://main--oklahoma--aemdemos.aem.live/ocsw/speakers-bureau
- After: https://issue-156--oklahoma--aemdemos.aem.live/ocsw/speakers-bureau
=> Style the Columns (multi-border) block

blocks/accordion/accordion.css
Fix #175
Test URLs:
- Before: https://main--oklahoma--aemdemos.aem.live/ocsw/owhof
- After: https://owhof-page--oklahoma--aemdemos.aem.live/ocsw/owhof
=> chore: accordion9 styles fix

blocks/header/header.css, scripts/scripts.js, styles/styles.css
Fix #178 
Test URLs:
- Before: https://main--oklahoma--aemdemos.aem.live/ocsw/about/membership
- After: https://issue-178--oklahoma--aemdemos.aem.live/ocsw/about/membership
=> feat: Back to top button

blocks/cards/cards.css, blocks/cards/cards.js
Fix #76 
Test URLs:
- Before: https://main--oklahoma--aemdemos.aem.live/
- After: https://fix-initiatives--oklahoma--aemdemos.aem.page/ocsw/initiatives
=> fixed initiatives page styling

blocks/cards/cards.css
Test URLs:
- Before: https://main--oklahoma--aemdemos.aem.live/
- After: https://fix-cards23--oklahoma--aemdemos.aem.page/ocsw/about/membership
=> added cards23 changes missed in last PR

blocks/cards/cards.css, blocks/cards/cards.js
Fix #194
Test URLs:
- Before: https://main--oklahoma--aemdemos.aem.live/ocsw/initiatives
- After: https://cards11-var-fix--oklahoma--aemdemos.aem.page/ocsw/initiatives
=> Changing cards11 to common name variant

blocks/cards/cards.css, blocks/cards/cards.js
Fix #193 
Test URLs:
- Before: https://main--oklahoma--aemdemos.aem.live/ocsw/about/membership
- After: https://cards23-var-fix--oklahoma--aemdemos.aem.page/ocsw/about/membership
=> Changing cards23 to common name variant
